[package]
name = "shapdf-wasm-example"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
shapdf = { path = "../../", default-features = false, features = ["wasm"] }

[lib]
crate-type = ["cdylib"]
